basePath: /
definitions:
  main.SongDetail:
    properties:
      link:
        example: https://www.youtube.com/watch?v=Xsp3_a-PMTw
        type: string
      releaseDate:
        example: 16.07.2006
        type: string
      text:
        example: |-
          Ooh baby, don't you know I suffer?
          Ooh baby, can you hear me moan?
          You caught me under false pretenses
          How long before you let me go?

          Ooh
          You set my soul alight
          Ooh
          You set my soul alight
        type: string
    type: object
info:
  contact: {}
  description: API для получения информации о песнях.
  title: Music info API
  version: 0.0.1
paths:
  /info:
    get:
      consumes:
      - application/json
      description: Получить данные о песне на основе группы и названия песни.
      parameters:
      - description: Название группы
        in: query
        name: group
        required: true
        type: string
      - description: Название песни
        in: query
        name: song
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.SongDetail'
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Получить информацию о песне
      tags:
      - songs
swagger: "2.0"
